# Trigger the workflow on pull request activity
on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, created, edited]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Deploy Pypi
        uses: remorses/pypi@v3
        with:
          setupfile: ./setup.py
          username: ${{ secrets.pypi_username }}
          password: ${{ secrets.pypi_password }}
